routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Deploy
Route::get('/deploy', 'DeployController@deploy')->name('deploy');

//Frontend Routes
Route::get('/', 'PageController@index')->name('index');
Route::get('/blog', 'PageController@getPostsByCategory')->name('blog.categories');
Route::get('blog/{slug}', 'PageController@show')->name('blog.show');
Route::post('/comments/{id}', 'CommentController@store')->name('comments.store');

//Backend Routes
Route::get('admin', function(){
  return redirect()->route('dashboard');
});
Route::group(['prefix' => 'backend'], function(){
  Route::get('/dashboard', 'BackendController@index')->name('dashboard');
  Route::resource('/users', 'UserController');
  Route::resource('/roles', 'RoleController');
  Route::resource('/permissions', 'PermissionController');
  Route::resource('/posts', 'PostController');
  Route::resource('/categories', 'CategoryController');
  Route::resource('/tags', 'TagController');
  Route::resource('/comments', 'CommentController', [ 'except' => ['store'] ]);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  public function category(){
      return $this->belongsTo('App\Category');
  }

  public function tags(){
      return $this->belongsToMany('App\Tag');
  }

  public function user(){
     return $this->hasOne('App\User', 'id', 'author_id');
  }

  public function comments(){
      return $this->hasMany('App\Comment');
  }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackendController extends Controller
{
    public function __construct()
    {
      $this->middleware('role:superadmin|admin|editor|author|contributor');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Auth;

class PostController extends Controller
{

    public function __construct()
    {
      $this->middleware('role:superadmin|admin|editor|author|contributor');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
       $posts = Post::orderBy('id', 'desc')->paginate(20);
       return view('backend.posts.index');//->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);
        $post = new Post;
        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->excerpt = $request->excerpt;
        $post->content = $request->content;
        $post->title = $request->title;
        $post->author_id = Auth::user()->id;
        $post->category_id = $request->category_id;
        $post->save();

        $post->tags()->sync($request->tags, false);

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $post = Post::find($id);
      return view('backend.posts.edit')->withPost($post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $post = Post::find($id);
      $post->title = $request->title;
      $post->slug = $request->slug;
      $post->excerpt = $request->excerpt;
      $post->content = $request->content;
      $post->title = $request->title;
      $post->author_id = Auth::user()->id;
      $post->category_id = $request->category_id;
      $post->save();

      $post->tags()->sync($request->tags, false);

      return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function apiCheckUnique(Request $request)
    {
      return json_encode(!Post::where('slug', '=', $request->slug)->exists());
    }
}

resources/views/backend/posts/create.blade.php
@extends('backend.includes.backend')
@section('stylesheets')

@endsection
@section('content')
    <div class="flex-container">
      <div class="columns m-t-10 m-b-0">
        <div class="column">
          <h1 class="title is-admin is-4">Add New Blog Post</h1>
        </div>
        <div class="column">
          {{-- <a href="{{ route('users.create') }}" class="button is-primary is-pulled-right"><i class="fa fa-user-plus m-r-10"></i> Create New User</a> --}}
        </div>
      </div>
      <form action="{{ route('posts.store') }}" method="post">
        {{ method_field('POST') }}
        {{ csrf_field() }}
        <div class="columns">
          <div class="column is-three-quarters-desktop is-three-quarters-tablet">
            <b-field>
              <b-input type="text" placeholder="Post Title" size="" v-model="title" name="title"></b-input>
            </b-field>

            <slug-widget url="{{url('/')}}" subdirectory="blog" :title="title" @copied="slugCopied" @slug-changed="updateSlug"></slug-widget>
            <input type="hidden" v-model="slug" name="slug" />

            <b-field class="m-t-20">
              <b-input type="textarea" name="excerpt" id="excerpt"
                  placeholder="Excerpt of your masterpiece..." rows="3">
              </b-input>
            </b-field>

            <categories></categories>
            <tags></tags>

            <b-field class="m-t-20">
              <b-input type="textarea" name="content" id="content"
                  placeholder="Compose your masterpiece..." rows="20">
              </b-input>
            </b-field>
          </div> <!-- end of .column.is-three-quarters -->

          <div class="column is-one-quarter-desktop is-narrow-tablet">
            <div class="card">
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <img class="is-rounded" src="https://placehold.it/50x50"/>
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-5" style="margin-bottom: 0px!important">{{Auth::user()->name}}</p>
                    <p class="subitle is-6">@jaikhlang</p>
                  </div>
                </div>
              </div>

              <div class="post-status-widget widget-area">
                <div class="status">
                  <div class="status-icon">
                    <b-icon icon="file" pack="fa" size="is-medium"></b-icon>
                  </div>
                  <div class="status-details">
                    <h4><span class="status-emphasis">Draft</span> Saved</h4>
                    <p>A Few Minutes Ago</p>
                  </div>
                </div>
              </div>
              <div class="publish-buttons-widget widget-area">
                <div class="secondary-action-button">
                  <button class="button is-info is-outlined is-fullwidth">Save Draft</button>
                </div>
                <div class="primary-action-button">
                  <button class="button is-primary is-fullwidth">Publish</button>
                </div>
              </div>
            </div>
          </div> <!-- end of .column.is-one-quarter -->
        </div>
      </form>
    </div> <!-- end of .flex-container -->
@endsection
@section('scripts')
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        title: '',
        slug: '',
        excerpt: '',
        content: '',
        api_token: '{{Auth::user()->api_token}}',
      },
      methods: {
        updateSlug: function(val) {
          this.slug = val;
        },
        slugCopied: function(type, msg, val) {
          notifications.toast(msg, {type: `is-${type}`});
        }
      }
    });
  </script>
@endsection

resources/views/backend/posts/edit.blade.php
@extends('backend.includes.backend')
@section('stylesheets')

@endsection
@section('content')
    <div class="flex-container">
      <div class="columns m-t-10 m-b-0">
        <div class="column">
          <h1 class="title is-admin is-4">Update Blog Post</h1>
        </div>
        <div class="column">
          {{-- <a href="{{ route('users.create') }}" class="button is-primary is-pulled-right"><i class="fa fa-user-plus m-r-10"></i> Create New User</a> --}}
        </div>
      </div>
      <form action="{{ route('posts.update', $post->id) }}" method="POST">
        {{ method_field('PUT') }}
        {{ csrf_field() }}
        <div class="columns">
          <div class="column is-three-quarters-desktop is-three-quarters-tablet">
            <b-field>
              <b-input type="text" placeholder="Post Title" size="" v-model="title" name="title"></b-input>
            </b-field>

            <slug-widget url="{{url('/')}}" subdirectory="blog" :title="title" @copied="slugCopied" @slug-changed="updateSlug"></slug-widget>
            <input type="hidden" v-model="slug" name="slug" />

            <b-field class="m-t-20">
              <b-input type="textarea" name="excerpt" id="excerpt" value="{{ $post->excerpt }}"
                  placeholder="Excerpt of your masterpiece..." rows="3">
              </b-input>
            </b-field>

            <categories></categories>
            <tags></tags>

            <b-field class="m-t-20">
              <b-input type="textarea" name="content" id="content" value="{{ $post->content }}"
                  placeholder="Compose your masterpiece..." rows="20">
              </b-input>
            </b-field>
          </div> <!-- end of .column.is-three-quarters -->

          <div class="column is-one-quarter-desktop is-narrow-tablet">
            <div class="card">
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <img class="is-rounded" src="https://placehold.it/50x50"/>
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-5" style="margin-bottom: 0px!important">{{Auth::user()->name}}</p>
                    <p class="subitle is-6">@jaikhlang</p>
                  </div>
                </div>
              </div>

              <div class="post-status-widget widget-area">
                <div class="status">
                  <div class="status-icon">
                    <b-icon icon="file" pack="fa" size="is-medium"></b-icon>
                  </div>
                  <div class="status-details">
                    <h4><span class="status-emphasis">Draft</span> Saved</h4>
                    <p>A Few Minutes Ago</p>
                  </div>
                </div>
              </div>
              <div class="publish-buttons-widget widget-area">
                <div class="secondary-action-button">
                  <button class="button is-info is-outlined is-fullwidth">Save Draft</button>
                </div>
                <div class="primary-action-button">
                  <button class="button is-primary is-fullwidth">Publish</button>
                </div>
              </div>
            </div>
          </div> <!-- end of .column.is-one-quarter -->
        </div>
      </form>
    </div> <!-- end of .flex-container -->
@endsection
@section('scripts')
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        title: '',
        slug: '',
        excerpt: '',
        content: '',
        api_token: '{{Auth::user()->api_token}}',
        isSelected: true
      },

      mounted(){
          return this.fetchPost()
      },

      methods: {
        updateSlug: function(val) {
          this.slug = val;
        },
        slugCopied: function(type, msg, val) {
          notifications.toast(msg, {type: `is-${type}`});
        },
        fetchPost: function() {
          axios.get('/api/post', {
            params: {
              id: {{ $post->id }}
            }
          }).then((response) => {
            this.title = response.data.title
            this.slug = response.data.slug
            this.excerpt = response.data.excerpt
            this.content = response.data.content
            this.category = response.data.category
          })
        }
      }
    });
  </script>
@endsection

resources/views/backend/posts/index.blade.php
@extends('backend.includes.backend')
@section('stylesheets')

@endsection
@section('content')
  <div class="flex-container">
    <div class="columns m-t-10">
      <div class="column">
        <h1 class="title">This is the posts.index page</h1>
      </div>
      <div class="column">
        <a href="{{ route('posts.create') }}" class="button is-primary is-pulled-right"><i class="fa fa-file m-r-10"></i> Create New Post</a>
      </div>
    </div>

    <posts></posts>
    {{--
    <div class="columns">
      <div class="column">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Title</th>
              <th>Slug</th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($posts as $post)
              <tr>
                <td>{{ $post->id }}</td>
                <td>{{ $post->title }}</td>
                <td>{{ $post->slug }}</td>
                <td></td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
    --}}

  </div> <!-- end of .flex-container -->
@endsection
@section('scripts')
  <script>
    var app = new Vue({
      el: '#app',
      data: {

      }
    });
  </script>
@endsection