routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Deploy
Route::get('/deploy', 'DeployController@deploy')->name('deploy');

//Frontend Routes
Route::get('/', 'PageController@index')->name('index');
Route::get('/blog', 'PageController@getPostsByCategory')->name('blog.categories');
Route::get('blog/{slug}', 'PageController@show')->name('blog.show');
Route::post('/comments/{id}', 'CommentController@store')->name('comments.store');

//Backend Routes
Route::get('admin', function(){
  return redirect()->route('dashboard');
});
Route::group(['prefix' => 'backend'], function(){
  Route::get('/dashboard', 'BackendController@index')->name('dashboard');
  Route::resource('/users', 'UserController');
  Route::resource('/roles', 'RoleController');
  Route::resource('/permissions', 'PermissionController');
  Route::resource('/posts', 'PostController');
  Route::resource('/categories', 'CategoryController');
  Route::resource('/tags', 'TagController');
  Route::resource('/comments', 'CommentController', [ 'except' => ['store'] ]);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/includes/navs/main.blade.php
<nav class="navbar is-transparent has-shadow is-fixed-top">
  <div class="navbar-brand">
    <a class="navbar-item" href="{{ url('/') }}">
      <img src="{{ asset('image/logo.png') }}" alt="Droidbook Logo" width="112" height="28">
    </a>
    <div class="navbar-burger burger" data-target="navbarDroidbook">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  @if (Request::segment(1) == "backend")
    <a class="navbar-item is-hidden-desktop" id="admin-slideout-button">
      <span class="icon">
        <i class="fa fa-arrow-circle-right"></i>
      </span>
    </a>
  @endif

  <div id="navbarDroidbook" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{{ url('/') }}">
        Home
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link" href="/documentation/overview/start/">
          Docs
        </a>
        <div class="navbar-dropdown is-boxed">
          <a class="navbar-item" href="/documentation/overview/start/">
            Overview
          </a>
          <a class="navbar-item" href="https://bulma.io/documentation/modifiers/syntax/">
            Modifiers
          </a>
          <a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">
            Columns
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="https://bulma.io/documentation/elements/box/">
            Elements
          </a>
          <a class="navbar-item is-active" href="https://bulma.io/documentation/components/breadcrumb/">
            Components
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      @guest
      <a href="{{ route('login') }}" class="navbar-item">Login</a>
      @else
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">Hey {{Auth::user()->name}}</a>
        <div class="navbar-dropdown is-right" >
          <a href="#" class="navbar-item">
            <span class="icon">
              <i class="fa fa-fw fa-user-circle-o m-r-5"></i>
            </span>Profile
          </a>

          <a href="#" class="navbar-item">
            <span class="icon">
              <i class="fa fa-fw fa-bell m-r-5"></i>
            </span>Notifications
          </a>
          @role('superadmin|admin')
          <a href="{{ route('dashboard') }}" class="navbar-item">
            <span class="icon">
              <i class="fa fa-fw fa-cog m-r-5"></i>
            </span>Manage
          </a>
          @endrole
          <hr class="navbar-divider">
          <a href="{{ route('logout') }}" class="navbar-item" onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
            <span class="icon">
              <i class="fa fa-fw fa-sign-out m-r-5"></i>
            </span>
            Logout
          </a>
          @include('backend.includes.forms.logout')
        </div>
      </div>
      @endguest
    </div>
  </div>
</nav>

resources/views/backend/includes/navs/manage.blade.php
<div class="side-menu " id="admin-side-menu">
  <aside class="menu m-t-30 m-l-10 m-r-10">
    <p class="menu-label">
      General
    </p>
    <ul class="menu-list">
      <li><a href="{{ route('dashboard') }}" class="">Dashboard</a></li>
    </ul>

    <p class="menu-label">
      Content
    </p>
    <ul class="menu-list">
      <li class="m-t-10">
        <a href="{{ route('posts.index') }}">Posts</a>
      </li>
      <li>
        <a href="{{ route('categories.index') }}">Categories</a>
      </li>
      <li>
        <a href="{{ route('tags.index') }}">Tags</a>
      </li>
      <li>
        <a href="{{ route('comments.index') }}">Comments</a>
      </li>
    </ul>

    @role('superadmin|admin')
    <p class="menu-label">
      Administration
    </p>
    <ul class="menu-list">
      <li><a href="{{route('users.index')}}" class="">Manage Users</a></li>
      <li>
        <a class="has-submenu">Roles &amp; Permissions</a>
        <ul class="submenu">
          <li><a href="{{ route('roles.index') }}" class="">Roles</a></li>
          <li><a href="{{ route('permissions.index') }}" class="">Permissions</a></li>
        </ul>
      </li>
    </ul>
    @endrole

  </aside>
</div